apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: ec14ad13ccf6b7e9d5722d2efeb574b9c81aa0f9
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: ec14ad13ccf6b7e9d5722d2efeb574b9c81aa0f9
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: ec14ad13ccf6b7e9d5722d2efeb574b9c81aa0f9