apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: b298b4ecbb2492a02b0e2ee63a7fda84fb10e6e1
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 00b3d65181dbb07b4cdedeb1388a245a18363176
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 00b3d65181dbb07b4cdedeb1388a245a18363176