run_all:
	jupyter run figure_1_and_2.ipynb
	jupyter run figure_3_and_4.ipynb
	jupyter run figure_5.ipynb
	jupyter run figure_6_and_7.ipynb
	jupyter run figure_8_9_10.ipynb
	jupyter run figure_11.ipynb
	jupyter run figure_12.ipynb
	jupyter run misc-compare-initialization-times.ipynb
	jupyter run misc-compare-SSTs.ipynb
	jupyter run misc-preprocess-for-rad-flux-mod

run_%:
	jupyter run $*.ipynb
