apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: deeec15c2532fe487913a8dfa60cb4696a3a8a76
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: deeec15c2532fe487913a8dfa60cb4696a3a8a76
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: deeec15c2532fe487913a8dfa60cb4696a3a8a76